name: Spotless

on: [push, pull_request]

jobs:
  spotless:
    name: "Spotless"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 10
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Check
        run: ./gradlew spotlessCheck -PspotlessRatchet=false
